# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
   
    - name: Set up Protobuf
      run: |
           sudo apt install protobuf-compiler
           protoc --version
           which protoc
           sudo ln -s /usr/bin/protoc /usr/local/bin/protoc
           
    - name: Clean Install w/ Maven
      run: 
        cd software/tritonsoccerai ; mvn clean install

    - name: Clean Compile w/ Maven
      run: 
        cd software/tritonsoccerai ; mvn clean compile assembly:single

    - name: Execute w/ Maven
      run: 
        cd software/tritonsoccerai ; mvn exec:java
