# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ai_debug_info.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ai_debug_info.proto',
  package='proto.triton',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x61i_debug_info.proto\x12\x0cproto.triton\".\n\x05\x44\x65\x62ug\x12%\n\x04path\x18\x01 \x01(\x0b\x32\x17.proto.triton.DebugPath\"\xc3\x01\n\tDebugPath\x12\n\n\x02id\x18\x01 \x01(\x05\x12*\n\x07\x66romPos\x18\x03 \x01(\x0b\x32\x19.proto.triton.DebugVector\x12(\n\x05toPos\x18\x04 \x01(\x0b\x32\x19.proto.triton.DebugVector\x12*\n\x07nextPos\x18\x05 \x01(\x0b\x32\x19.proto.triton.DebugVector\x12(\n\x05nodes\x18\x02 \x03(\x0b\x32\x19.proto.triton.DebugVector\"#\n\x0b\x44\x65\x62ugVector\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x62\x06proto3')
)




_DEBUG = _descriptor.Descriptor(
  name='Debug',
  full_name='proto.triton.Debug',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='proto.triton.Debug.path', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=83,
)


_DEBUGPATH = _descriptor.Descriptor(
  name='DebugPath',
  full_name='proto.triton.DebugPath',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.triton.DebugPath.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fromPos', full_name='proto.triton.DebugPath.fromPos', index=1,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='toPos', full_name='proto.triton.DebugPath.toPos', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nextPos', full_name='proto.triton.DebugPath.nextPos', index=3,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='nodes', full_name='proto.triton.DebugPath.nodes', index=4,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=281,
)


_DEBUGVECTOR = _descriptor.Descriptor(
  name='DebugVector',
  full_name='proto.triton.DebugVector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='proto.triton.DebugVector.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='proto.triton.DebugVector.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=318,
)

_DEBUG.fields_by_name['path'].message_type = _DEBUGPATH
_DEBUGPATH.fields_by_name['fromPos'].message_type = _DEBUGVECTOR
_DEBUGPATH.fields_by_name['toPos'].message_type = _DEBUGVECTOR
_DEBUGPATH.fields_by_name['nextPos'].message_type = _DEBUGVECTOR
_DEBUGPATH.fields_by_name['nodes'].message_type = _DEBUGVECTOR
DESCRIPTOR.message_types_by_name['Debug'] = _DEBUG
DESCRIPTOR.message_types_by_name['DebugPath'] = _DEBUGPATH
DESCRIPTOR.message_types_by_name['DebugVector'] = _DEBUGVECTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Debug = _reflection.GeneratedProtocolMessageType('Debug', (_message.Message,), dict(
  DESCRIPTOR = _DEBUG,
  __module__ = 'ai_debug_info_pb2'
  # @@protoc_insertion_point(class_scope:proto.triton.Debug)
  ))
_sym_db.RegisterMessage(Debug)

DebugPath = _reflection.GeneratedProtocolMessageType('DebugPath', (_message.Message,), dict(
  DESCRIPTOR = _DEBUGPATH,
  __module__ = 'ai_debug_info_pb2'
  # @@protoc_insertion_point(class_scope:proto.triton.DebugPath)
  ))
_sym_db.RegisterMessage(DebugPath)

DebugVector = _reflection.GeneratedProtocolMessageType('DebugVector', (_message.Message,), dict(
  DESCRIPTOR = _DEBUGVECTOR,
  __module__ = 'ai_debug_info_pb2'
  # @@protoc_insertion_point(class_scope:proto.triton.DebugVector)
  ))
_sym_db.RegisterMessage(DebugVector)


# @@protoc_insertion_point(module_scope)
