# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_simulation_custom_erforce_robot_spec.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ssl_simulation_custom_erforce_robot_spec.proto',
  package='sslsim',
  syntax='proto2',
  serialized_options=_b('Z6github.com/RoboCup-SSL/ssl-simulation-protocol/pkg/sim'),
  serialized_pb=_b('\n.ssl_simulation_custom_erforce_robot_spec.proto\x12\x06sslsim\"Y\n\x10RobotSpecErForce\x12\x14\n\x0cshoot_radius\x18\x01 \x01(\x02\x12\x17\n\x0f\x64ribbler_height\x18\x02 \x01(\x02\x12\x16\n\x0e\x64ribbler_width\x18\x03 \x01(\x02\x42\x38Z6github.com/RoboCup-SSL/ssl-simulation-protocol/pkg/sim')
)




_ROBOTSPECERFORCE = _descriptor.Descriptor(
  name='RobotSpecErForce',
  full_name='sslsim.RobotSpecErForce',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shoot_radius', full_name='sslsim.RobotSpecErForce.shoot_radius', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dribbler_height', full_name='sslsim.RobotSpecErForce.dribbler_height', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dribbler_width', full_name='sslsim.RobotSpecErForce.dribbler_width', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=147,
)

DESCRIPTOR.message_types_by_name['RobotSpecErForce'] = _ROBOTSPECERFORCE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RobotSpecErForce = _reflection.GeneratedProtocolMessageType('RobotSpecErForce', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTSPECERFORCE,
  __module__ = 'ssl_simulation_custom_erforce_robot_spec_pb2'
  # @@protoc_insertion_point(class_scope:sslsim.RobotSpecErForce)
  ))
_sym_db.RegisterMessage(RobotSpecErForce)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
